apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.postgres.secret.dbName }}
  DB_USER: {{ .Values.postgres.secret.dbUser }}
  DB_PASSWORD: {{ .Values.postgres.secret.dbPassword }}
