sonar.projectKey=spring-petclinic-angular
sonar.organization=adnagrbestic
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/docs/**,**/e2e/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/test.ts,**/environments/**
